momnameandage =input("what is your mom's name and age: ")
print("userquestion")
dadnameandage =input("what is your dad's name and age: ")
print("dadnameandage")
whatisyourpetsnameandage =input("what is your pets name and age: ")
print("whatisyourpetsnameandage")
mynameandage =input("what is your name and age: ")
print("mynameandage")
howmanyyearsyouwillbeafter15years =input("how many years you will be after 15 years: ")
print("howmanyyearsyoywillbeafter15years")
print("mynameandage+15")